import type { ICountry } from "~/types/contry";

export const countries: ICountry[] = [
  { name: 'Perú', abbreviation: 'PE', code_phone: '+51' },
  { name: 'Argentina', abbreviation: 'AR', code_phone: '+54' },
  { name: 'Brazil', abbreviation: 'BR', code_phone: '+55' },
  { name: 'Chile', abbreviation: 'CL', code_phone: '+56' },
  { name: 'Colombia', abbreviation: 'CO', code_phone: '+57' },
  { name: 'Ecuador', abbreviation: 'EC', code_phone: '+593' },
  { name: 'Mexico', abbreviation: 'MX', code_phone: '+52' },
  { name: 'Afghanistan', abbreviation: 'AF', code_phone: '+93' },
  { name: 'Albania', abbreviation: 'AL', code_phone: '+355' },
  { name: 'Algeria', abbreviation: 'DZ', code_phone: '+213' },
  { name: 'Andorra', abbreviation: 'AD', code_phone: '+376' },
  { name: 'Angola', abbreviation: 'AO', code_phone: '+244' },
  { name: 'Armenia', abbreviation: 'AM', code_phone: '+374' },
  { name: 'Australia', abbreviation: 'AU', code_phone: '+61' },
  { name: 'Austria', abbreviation: 'AT', code_phone: '+43' },
  { name: 'Azerbaijan', abbreviation: 'AZ', code_phone: '+994' },
  { name: 'Bahamas', abbreviation: 'BS', code_phone: '+1-242' },
  { name: 'Bahrain', abbreviation: 'BH', code_phone: '+973' },
  { name: 'Bangladesh', abbreviation: 'BD', code_phone: '+880' },
  { name: 'Barbados', abbreviation: 'BB', code_phone: '+1-246' },
  { name: 'Belarus', abbreviation: 'BY', code_phone: '+375' },
  { name: 'Belgium', abbreviation: 'BE', code_phone: '+32' },
  { name: 'Belize', abbreviation: 'BZ', code_phone: '+501' },
  { name: 'Benin', abbreviation: 'BJ', code_phone: '+229' },
  { name: 'Bhutan', abbreviation: 'BT', code_phone: '+975' },
  { name: 'Bolivia', abbreviation: 'BO', code_phone: '+591' },
  { name: 'Bosnia and Herzegovina', abbreviation: 'BA', code_phone: '+387' },
  { name: 'Botswana', abbreviation: 'BW', code_phone: '+267' },
  { name: 'Brunei', abbreviation: 'BN', code_phone: '+673' },
  { name: 'Bulgaria', abbreviation: 'BG', code_phone: '+359' },
  { name: 'Burkina Faso', abbreviation: 'BF', code_phone: '+226' },
  { name: 'Burundi', abbreviation: 'BI', code_phone: '+257' },
  { name: 'Cambodia', abbreviation: 'KH', code_phone: '+855' },
  { name: 'Cameroon', abbreviation: 'CM', code_phone: '+237' },
  { name: 'Canada', abbreviation: 'CA', code_phone: '+1' },
  { name: 'Cape Verde', abbreviation: 'CV', code_phone: '+238' },
  { name: 'Central African Republic', abbreviation: 'CF', code_phone: '+236' },
  { name: 'Chad', abbreviation: 'TD', code_phone: '+235' },
  { name: 'China', abbreviation: 'CN', code_phone: '+86' },
  { name: 'Congo', abbreviation: 'CG', code_phone: '+242' },
  { name: 'Costa Rica', abbreviation: 'CR', code_phone: '+506' },
  { name: 'Croatia', abbreviation: 'HR', code_phone: '+385' },
  { name: 'Cuba', abbreviation: 'CU', code_phone: '+53' },
  { name: 'Cyprus', abbreviation: 'CY', code_phone: '+357' },
  { name: 'Czech Republic', abbreviation: 'CZ', code_phone: '+420' },
  { name: 'Denmark', abbreviation: 'DK', code_phone: '+45' },
  { name: 'Djibouti', abbreviation: 'DJ', code_phone: '+253' },
  { name: 'Dominica', abbreviation: 'DM', code_phone: '+1-767' },
  { name: 'Dominican Republic', abbreviation: 'DO', code_phone: '+1-809' },
  { name: 'Egypt', abbreviation: 'EG', code_phone: '+20' },
  { name: 'El Salvador', abbreviation: 'SV', code_phone: '+503' },
  { name: 'Estonia', abbreviation: 'EE', code_phone: '+372' },
  { name: 'Finland', abbreviation: 'FI', code_phone: '+358' },
  { name: 'France', abbreviation: 'FR', code_phone: '+33' },
  { name: 'Germany', abbreviation: 'DE', code_phone: '+49' },
  { name: 'Greece', abbreviation: 'GR', code_phone: '+30' },
  { name: 'Guatemala', abbreviation: 'GT', code_phone: '+502' },
  { name: 'Honduras', abbreviation: 'HN', code_phone: '+504' },
  { name: 'India', abbreviation: 'IN', code_phone: '+91' },
  { name: 'Indonesia', abbreviation: 'ID', code_phone: '+62' },
  { name: 'Ireland', abbreviation: 'IE', code_phone: '+353' },
  { name: 'Israel', abbreviation: 'IL', code_phone: '+972' },
  { name: 'Italy', abbreviation: 'IT', code_phone: '+39' },
  { name: 'Japan', abbreviation: 'JP', code_phone: '+81' },
  { name: 'Kenya', abbreviation: 'KE', code_phone: '+254' },
  { name: 'Malaysia', abbreviation: 'MY', code_phone: '+60' },
  { name: 'Netherlands', abbreviation: 'NL', code_phone: '+31' },
  { name: 'New Zealand', abbreviation: 'NZ', code_phone: '+64' },
  { name: 'Nigeria', abbreviation: 'NG', code_phone: '+234' },
  { name: 'Norway', abbreviation: 'NO', code_phone: '+47' },
  { name: 'Pakistan', abbreviation: 'PK', code_phone: '+92' },
  { name: 'Panama', abbreviation: 'PA', code_phone: '+507' },
  { name: 'Paraguay', abbreviation: 'PY', code_phone: '+595' },
  { name: 'Philippines', abbreviation: 'PH', code_phone: '+63' },
  { name: 'Poland', abbreviation: 'PL', code_phone: '+48' },
  { name: 'Portugal', abbreviation: 'PT', code_phone: '+351' },
  { name: 'Qatar', abbreviation: 'QA', code_phone: '+974' },
  { name: 'Romania', abbreviation: 'RO', code_phone: '+40' },
  { name: 'Russia', abbreviation: 'RU', code_phone: '+7' },
  { name: 'Saudi Arabia', abbreviation: 'SA', code_phone: '+966' },
  { name: 'South Africa', abbreviation: 'ZA', code_phone: '+27' },
  { name: 'Spain', abbreviation: 'ES', code_phone: '+34' },
  { name: 'Sri Lanka', abbreviation: 'LK', code_phone: '+94' },
  { name: 'Sweden', abbreviation: 'SE', code_phone: '+46' },
  { name: 'Switzerland', abbreviation: 'CH', code_phone: '+41' },
  { name: 'Turkey', abbreviation: 'TR', code_phone: '+90' },
  { name: 'United Kingdom', abbreviation: 'GB', code_phone: '+44' },
  { name: 'United States', abbreviation: 'US', code_phone: '+1' },
  { name: 'Uruguay', abbreviation: 'UY', code_phone: '+598' },
  { name: 'Venezuela', abbreviation: 'VE', code_phone: '+58' },
  { name: 'Vietnam', abbreviation: 'VN', code_phone: '+84' },
  { name: 'Zambia', abbreviation: 'ZM', code_phone: '+260' },
  { name: 'Zimbabwe', abbreviation: 'ZW', code_phone: '+263' }
];